export let startSequence = [
  { time: -30, imgrow: false, attention: false },
  { time: 0, sound: "start", ap: false, xgt: true, untilrow: false, flag: "", flagrow: false },
  { time: 1, sound: "triple" },
  { time: 2, sound: "triple" },
  { time: 3, sound: "triple" },
  { time: 4, sound: "triple" },
  { time: 5, sound: "triple", flag: "class down" },
  { time: 6, sound: "double" },
  { time: 7, sound: "double" },
  { time: 8, sound: "double" },
  { time: 9, sound: "double" },
  { time: 10, sound: "double", flag: "class down" },
  { time: 11, sound: "single" },
  { time: 12, sound: "single" },
  { time: 13, sound: "single" },
  { time: 14, sound: "single" },
  { time: 15, sound: "single", flag: "class down" },
  { time: 16, sound: "prep" },
  { time: 30, flag: "class down" },
  { time: 45, flag: "class down" },
  { time: 55, flag: "class down" },
  { time: 60, sound: "longer", flag: "" },
  { time: 61, sound: "single", flag: "P down" },
  { time: 62, sound: "single" },
  { time: 63, sound: "single" },
  { time: 64, sound: "single" },
  { time: 65, sound: "single" },
  { time: 66, sound: "prep" },
  { time: 119, flag: "P down" },
  { time: 240, sound: "longer", flag: "" },
  { time: 241, sound: "single", flag: "P up" },
  { time: 242, sound: "single" },
  { time: 243, sound: "single" },
  { time: 244, sound: "single" },
  { time: 245, sound: "single", flag: "P up" },
  { time: 246, sound: "prep" },
  { time: 299, flag: "P up" },
  { time: 300, sound: "longer", flag: "", imgrow: true, ap: true },
  { time: 301, sound: "single", flag: "class up" },
  { time: 302, sound: "single" },
  { time: 303, sound: "single" },
  { time: 304, sound: "single" },
  { time: 305, sound: "single", flag: "class up" },
  { time: 306, sound: "prep" },
  { time: 320, sound: "attention", flagrow: true },
  { time: 330, flag: "class up", flagrow: true, attention: true },
];
